### ISSUE TITLE
How can i style the checkbox component?

### ISSUE THREAD

**Issue by CrispenGari** [ThakurBallary/react-native-btr-demo#30]
I want to use the component `Checkbox` and customize the styles of the `checkbox` but as it seems the only props this component is taking are:

1. `color`
2. `disabled`
3. `checked`
4. `onPress`

```tsx
 <CheckBox
              color={COLORS.tertiary}
              disabled={false}
              checked={agree}
              onPress={() => setAgree((state) => !state)}
            />
```

> I want to customize the container style of the checkbox and change the border radius to `3px`. Is it possible that you can update your package to the version that gives us this flexibility?

**Comment by julio-nt** [comment]
Hey, @CrispenGari you can make those changes if you go directly into the component.

So if you want to change the checkbox border radius you can go to its file (node_modules > react-native-btr > src > checkbox) and change the border radius directly there or add props for this so you can set it differently anytime you want.

**Comment by CrispenGari** [comment]
@julio-nt  Thank you for your response. I know i can do that, but i thought it will be better to generalize a component using props in the core package rather than going it that route, because when i install packages my changes will be lost. So i will need to revisit `📁 node_modules > react-native-btr > src > checkbox` again.

**Comment by julio-nt** [comment]
@CrispenGari Interesting. I didn't know that. I made a pull request with a small change, focusing only on borderRadius and borderWidth. I wish I could do more, but right now, I'm busy, and I'm not really used to React Native to make significant changes. However, I hope the creator of this package accepts my request or makes even better changes himself because I've been loving this package.

**Comment by ThakurBallary** [comment]
In `v2.2.1` `borderRadius` and `borderWidth` have been added.

@julio-nt Thanks for the [Pull Request](https://github.com/ThakurBallary/react-native-btr/pull/22)
